export const CONTACT_SHOW_ADD_CONTACT_PANEL = 'CONTACT_SHOW_ADD_CONTACT_PANEL';
export const CONTACT_SEARCH_FOR_CONTACTS = 'CONTACT_SEARCH_FOR_CONTACTS';
export const CONTACT_CONTACT_SELECTED = 'CONTACT_CONTACT_SELECTED';
export const CONTACT_CONTACTS_LOADED = 'CONTACT_CONTACTS_LOADED';
